package com.app.ellp.Module.Responsavel.Enums;

public enum Escolaridade {
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    ENSINO_SUPERIOR_INCOMPLETO,
    ENSINO_SUPERIOR_COMPLETO,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO,
    ANALFABETO,
    OUTROS
}